ToDoList_project/ToDoList_project/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       # Examples:s
                       # url(r'^$', 'ToDoList_project.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^to_do_list/', include('to_do_list.urls')), # ADD THIS NEW TUPLE
                       url(r'', include('to_do_list.urls')), # ADD THIS NEW TUPLE

)

ToDoList_project/to_do_list/urls.py
from django.conf.urls import patterns, url
from to_do_list import views

urlpatterns = patterns('',
        url(r'^$', views.login, name='login'),
        url(r'^register/$', views.register, name='register'),
        url(r'^logout/$', views.user_logout, name='logout'),
        url(r'^mainpage/$', views.mainpage, name='mainpage'),
        #url(r'^createtask/(?P<group_id_url>\w+)/$', views.createtask, name='createtask'),
        url(r'^createtask/$', views.createtask, name='createtask'),
        url(r'^viewgroup/(?P<group_name_url>\w+)/$', views.viewgroup, name='viewgroup'),
        url(r'^edittask/(?P<task_id_url>\w+)/$', views.edittask, name='edittask'),
        url(r'^creategrp/(?P<user_id>\w+)/$', views.creategrp, name='creategrp'),





)

ToDoList_project/to_do_list/models.py
from django.db import models
from django.contrib.auth.models import User


PRIORITY_CHOICES = (

    (1, 'Low'), (2, 'Normal'), (3, 'High'),

)


# Create your models here.
class UserProfile(models.Model):
    UserProName = models.OneToOneField(User, unique=True)   # GUID
    FirstName = models.CharField(max_length=128)
    LastName = models.CharField(max_length=128)


    def __unicode__(self):
        return unicode(self.UserProName)


class Group(models.Model):
    Creator = models.ForeignKey(UserProfile)
    GroupName = models.CharField(max_length=128)
    GroupDescription = models.TextField()

    def __unicode__(self):
        return self.GroupName

# a user can be a member of itself
class Memberof(models.Model):
    MemberName = models.ForeignKey(UserProfile)
    MemGroupName = models.ForeignKey(Group)



    def __unicode__(self):
        return self.MemberName




class Task(models.Model):
    User = models.ForeignKey(UserProfile)
    Group = models.ForeignKey(Group)
    TaskName = models.TextField()
    Details = models.TextField()
    Priority = models.IntegerField(choices=PRIORITY_CHOICES, default=2)
    Completed = models.BooleanField(default=False)
    StartDate = models.DateField()
    EndDate = models.DateField()

    def __unicode__(self):
        return self.TaskName

ToDoList_project/templates/creategrp.html
{% extends 'header.html' %}
{% block body_block %}


 <a href="{% url 'mainpage' %}" class="btn btn-lg btn-info" role="button">Main Page</a><br/>
    <br/>
<form id="creategrp" method="post" action="">

  {% csrf_token %}

    {{ form }}



<br/>
 <button type="submit" value="submit" class="btn btn-lg btn-primary">create Group</button>

</form>












{% endblock %}

ToDoList_project/templates/createtask.html
{% extends 'header.html' %}
{% block body_block %}
 <script>


         $(function() {
        $( "#id_myDate" ).datepicker();
    });
         $(function() {
        $( "#id_endDate" ).datepicker();
    });
	</script>


<form id="Task_form" method="post" action="/to_do_list/createtask/">

  {% csrf_token %}


    Assign to:{{ form.User }}
    <br/>
   Group: {{ form.Group }}
    <br/>
   Task Name: {{ form.TaskName }}
    <br/>
   Task Details: {{ form.Details  }}
    <br/>
   Task Priority: {{ form.Priority }}
    <br/>
    start Date: <input type="text" name="StartDate" id="id_myDate">
    <br/>
    End Date: <input type="text" name="EndDate" id="id_endDate">
    <br/>



 <button type="submit" value="submit" class="btn btn-lg btn-primary">Category</button>

</form>












{% endblock %}

ToDoList_project/templates/edittask.html
{% extends 'header.html' %}
{% block body_block %}
   {% load i18n %}

 <script>


 $(function() {
        $( ".datepicker" ).datepicker();
    });




	</script>





   <form action="" method="POST">
   {% csrf_token %}
       {{ userform.management_form }}
     <h3>Group of this Task: {{ task.Group }}</h3>

    {{ userform }}



   <br/>
      <a href="/to_do_list/mainpage/" class="btn btn-info" role="button">Cancel</a>
       <input id="commp" type="submit" name="editform" value="update" class="btn btn-info">
 </form>
















{% endblock %}

ToDoList_project/templates/header.html
<!DOCTYPE html>
{% load static %} <!-- for loading static media -->

<html lang="en">

<head>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">


    <link href="{% static 'css/bootstrap-responsive.min.css' %}" rel="stylesheet">
    <script language="JavaScript" src="{% static 'js/htmlDatePicker.js' %}" type="text/javascript"></script>
    <link href="{% static 'css/htmlDatePicker.css' %}" rel="stylesheet"/>
    <script src="{% static 'js/jquery-2.1.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'js/jquery.ui.core.js' %}"></script>
    <script src="{% static 'js/jquery.ui.widget.js' %}"></script>
    <script src="{% static 'js/jquery.ui.accordion.js' %}"></script>
    <script src="{% static 'js/jquery.ui.datepicker.js' %}"></script>
    <script src="{% static 'js/jExpand.js' %}"></script>


    <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">


    <title>{% block title %}We Do List{% endblock %}</title>

</head>

<body>
<div style="max-width:800px; margin:0 auto;">
<div class="row-fluid" style="margin-top: 10px">


    <div class="span3">
        <img src="{% static "img/logo.png" %}" alt="Welcome to We-do-list"/>
    </div>
    {% if user.is_authenticated %}
        <h3>{{ user.username }}</h3>
        <a href="{% url "logout" %}" class="btn btn-lg btn-info" role="button">Logout</a><br/>

    {% else %}
        <h3></h3>
    {% endif %}


</div>

<div class="container-fluid">
    <div style="max-width: 850px">
        {% block body_block %}{% endblock %}
    </div>
</div>
</div>

</body>
</html>

ToDoList_project/templates/login.html
{% extends 'header.html' %}

{% block body_block %}

    <h1>Login to todolist</h1>

        <form id="login_form" method="post" action="">
            <p>{% csrf_token %}            </p>

                <div class="input-group input-group-lg">
                <span class="input-group-addon">Username</span>
                <input type="text" class="form-control" name="username" placeholder="username">

            </p>
            <p>

                <span class="input-group-addon">Password</span>
                <input type="password" class="form-control" name="password" placeholder="password">
                </div>
              <br />

             <a href="{% url "register" %}" class="btn btn-lg btn-primary" role="button">Register</a>&nbsp;
            <button type="submit" value="submit" class="btn btn-lg btn-primary">&nbsp;Login&nbsp;</button>





            </p>
        </form>
{% endblock %}

ToDoList_project/templates/mainpage.html
{% extends 'header.html' %}

{% block body_block %}


    <h1>Welome</h1>


<a href="{% url "createtask" %}" class="btn btn-lg btn-info" role="button">Create New Task</a>
    &nbsp;
<a href="/to_do_list/creategrp/{{ userprofile }}" class="btn btn-lg btn-info" role="button">Create New Group</a>
<br/>
<br/>

    <div class="accordion" id="accordion2"
         style="background-color: #ffffff;border: 2px darkgray;border-radius: 10px;padding: 0 8px;">
    <form action="" method="POST">
    <div class="accordion-group" style="border-color: #ffffff">

        <div class="accordion-heading">
            <a class="accordion-toggle btn btn-block" data-toggle="collapse" data-parent="#accordion2"
               href="#collapseOne">Incomplete Task</a>
        </div>

        <div id="collapseOne" class="accordion-body collapse in">
            <div class="accordion-inner">


                {% csrf_token %}

                {% if task_d %}




                    <div class="panel-group" id="accordion">


                        <div class="panel panel-default">
                        <table class="table table-hover"><tr>
                            <th>Task name</th><th>Set completed</th>
                            </tr>
                            {% for task in task_d %}
                                <tr>
                               <!-- <td>-->
                                <div class="panel-heading">
                                    <!--<table class="table table-hover">-->

                                        <!--<tr>-->
                                            <td>
                                                <h5 class="panel-title">
                                                    <a data-toggle="collapse" data-parent="#accordion"
                                                       href="#collapse{{ task.id }}">
                                                        {{ task.TaskName }}
                                                    </a>
                                                </h5>
                                            </td>
                                            <td>
                                                <input type="checkbox" name="mark_done"
                                                                    value="{{ task.id }}"
                                                                    id="mark_done_{{ task.id }}">
                                            </td>
                                            <td>
                                                <a href="/to_do_list/edittask/{{ task.id }}"
                                                   class="btn btn-info btn-small"
                                                   role="button">edit task</a>
                                            </td>
                                        <!--</tr>-->
                                    <!--</table>-->
                                </div>
                               <!-- </td>-->
                                </tr>
                                <tr>
                                <td>
                                <div id="collapse{{ task.id }}" class="panel-collapse collapse">
                                    <div class="panel-body">
                                        <table><tr>
                                        <td>
                                        <ul style="list-style: none">
                                            <li><b>Group:</b></li>
                                            <li><b>Details:</b>
                                            <li><b>Priority:</b>
                                            <li><b>Start Date:</b>
                                            <li><b>End Date:</b>
                                        </ul>
                                            </td>
                                           <td>
                                        <ul style="list-style: none">
                                            <li>{{ task.Group }}</li>
                                            <li>{{ task.Details }}</li>
                                            <li>{{ task.get_Priority_display }}</li>
                                            <li>{{ task.StartDate }}</li>
                                            <li>{{ task.EndDate }}</li>
                                        </ul>
                                            </td>
                                    </tr></table>
                                    </div>
                                </div>
                                </td>
                                </tr>
                            {% endfor %}
                        </table>
                        </div>


                    </div>
<input id="mark_tasks_done" type="submit" name="mark_tasks_done" value="update"
                                        class="btn btn-info">




                {% else %}
                    <strong>You do not have Task Currently</strong>
                {% endif %}


            </div>
        </div>
    </div>
    <div class="accordion-group" style="border-color: #ffffff">

        <div class="accordion-heading">
            <a class="accordion-toggle btn btn-block" data-toggle="collapse" data-parent="#accordion2"
               href="#collapseTwo">My Groups</a>
        </div>

        <div id="collapseTwo" class="accordion-body collapse">
            <div class="accordion-inner">


                {% if groupin %}

                    <ul>
                        <b>click on the group name to manage group task. Personal task are consider as a group.</b>
                        {% for groupin in groupin %}
                            <li><a href="/to_do_list/viewgroup/{{ groupin.url }}">{{ groupin.MemGroupName }}</a>
                            </li>

                        {% endfor %}
                    </ul>
                {% else %}
                    <strong>No group.</strong>
                {% endif %}


            </div>
        </div>
    </div>
    <div class="accordion-group" style="border-color: #ffffff">

        <div class="accordion-heading">
            <a class="accordion-toggle btn btn-block" data-toggle="collapse" data-parent="#accordion2"
               href="#collapsethree">Completed Task</a>
        </div>

        <div id="collapsethree" class="accordion-body collapse in">
            <div class="accordion-inner">
<!-------------------------------------------------------------------------------------------->

                {% if task_c %}

				 <div class="panel-group" id="accordion">
					<div class="panel panel-default">

                    <table class="table table-hover">

                        <tr>
                            <th>Task Name</th>
                            <th>set to incomplete</th>
                            <th>Delete Task</th>
                        </tr>
                        {% for task in task_c %}


                            <tr>

							 <div class="panel-heading">
                                <td>
                                   <h5 class="panel-title">
                                                    <a data-toggle="collapse" data-parent="#accordion"
                                                       href="#collapse{{ task.id }}">
                                                        {{ task.TaskName }}
                                                    </a>
                                                </h5>
                                </td>
                                <td>
                                    {{ task.id }}<input type="checkbox" name="undo_completed_task"value="{{ task.id }}"id="id_undo_completed_task{{ task.id }}">
                                </td>
                                <td>
                                    <input type="checkbox" name="del_task" value="{{ task.id }}"id="del_task_{{ task.id }}">
                                </td>
							</div>
                            </tr>

                            <tr>
                                <td>
                                   <div id="collapse{{ task.id }}" class="panel-collapse collapse">
                                    <div class="panel-body">
                                        <table><tr>
                                        <td>
                                        <ul style="list-style: none">
                                            <li><b>Group:</b></li>
                                            <li><b>Details:</b>
                                            <li><b>Priority:</b>
                                            <li><b>Start Date:</b>
                                            <li><b>End Date:</b>
                                        </ul>
                                            </td>
                                           <td>
                                        <ul style="list-style: none">
                                            <li>{{ task.Group }}</li>
                                            <li>{{ task.Details }}</li>
                                            <li>{{ task.get_Priority_display }}</li>
                                            <li>{{ task.StartDate }}</li>
                                            <li>{{ task.EndDate }}</li>
                                        </ul>
                                            </td>
                                    </tr></table>
                                    </div>
                                </div>
                                </td>

                            </tr>


                        {% endfor %}


                    </table>
				</div>
                  </div>
                    <input id="mark_task_undone" type="submit" name="mark_task_undone" value="update"
                                       class="btn btn-info">
                {% else %}
                    <strong>You do not have Completed Task Currently</strong>
                {% endif %}

<!----------------------------------------------------------------------------------->
            </div>
        </div>
    </div>


    </form>
    </div>



{% endblock %}

ToDoList_project/templates/register.html
{% extends 'header.html' %}

{% block body_block %}
        {% if registered %}
         <strong>thank you for registering!</strong>
        <a href="{% url "login" %}"class="btn btn-lg btn-success" role="button">Return to the homepage.</a>

          <br />
        {% else %}
        <h3>register here!</h3><br />

            <a href="{% url "login" %}" class="btn btn-lg btn-info" role="button">Return to Login page.</a><br/>
            <br/>

        <form id="user_form" method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}

            <!-- Display each form. The as_p method wraps each element in a paragraph
                 (<p>) element. This ensures each element appears on a new line,
                 making everything look neater. -->
            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <!-- Provide a button to click to submit the form. -->

        <button type="submit" name="submit" value="Register" class="btn btn-lg btn-primary">Register</button>

        </form>
        {% endif %}
{% endblock %}

ToDoList_project/templates/viewgroup.html
{% extends 'header.html' %}
{% block body_block %}

      <h1>{{ group_name }}</h1>
   <!--  <a href="/to_do_list/createtask/{{ grp.id }}" class="btn btn-lg btn-info" role="button">Create New Task</a><br/>-->
    <a href="{% url 'mainpage' %}" class="btn btn-lg btn-info" role="button">Main Page</a><br/>
    <br/>
            {% if task %}
            <ul>
                {% for t in task %}
                <li><b>Task Name:</b> {{ t.TaskName }}</li>
                    <li><b>Details:</b> {{ t.Details }}</li>
                    <li><b>Priority:</b> {{ t.get_Priority_display }}</li>
                    <li><b>Completed:</b> {{ t.Completed }}</li>
                    <li><b>Start/End Date:</b> {{ t.StartDate }}/ {{ t.EndDate }}</li>
                    <hr>
                {% endfor %}
            </ul>
            {% else %}
                <strong>No Task in this group.</strong>
            {% endif %}
     <h1>group members</h1>

            {% if members %}
            <ul>
                {% for m in members %}
                <li><b>Member Name:</b> {{ m.MemberName }}</li>

                {% endfor %}
            </ul>
            {% else %}
                <strong>No Task in this group.</strong>
            {% endif %}














{% endblock %}